#pragma once

// Boost Software License - Version 1.0 - August 17th, 2003

// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:

// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.


// This file contains test cases derived from:
// https://github.com/ulfjack/ryu
// See xcharconv_ryu.h for the exact commit.
// (Keep the cgmanifest.json commitHash in sync.)

#include "test_base.hpp"

// clang-format off

inline constexpr float_to_string_test_case<float, char> float_to_string_test_cases[] = {
    // Test special cases (zero, inf, nan) and an ordinary case. Also test negative signs.
    {0.0f, str::float_format::scientific, 0, "0e0"},
    {-0.0f, str::float_format::scientific, 0, "-0e0"},
    {float_inf, str::float_format::scientific, "inf"},
    {-float_inf, str::float_format::scientific, "-inf"},
    {float_nan, str::float_format::scientific, "nan"},
    {-float_nan, str::float_format::scientific, "-nan(ind)"},
    {float_nan_payload, str::float_format::scientific, "nan"},
    {-float_nan_payload, str::float_format::scientific, "-nan"},
    {2.018f, str::float_format::scientific, 3, "2.018e0"},
    {-2.018f, str::float_format::scientific, 3, "-2.018e0"},

    // Ditto for fixed, which doesn't emit exponents.
    {0.0f, str::float_format::fixed, 0, "0"},
    {-0.0f, str::float_format::fixed, 0, "-0"},
    {float_inf, str::float_format::fixed, "inf"},
    {-float_inf, str::float_format::fixed, "-inf"},
    {float_nan, str::float_format::fixed, "nan"},
    {-float_nan, str::float_format::fixed, "-nan(ind)"},
    {float_nan_payload, str::float_format::fixed, "nan"},
    {-float_nan_payload, str::float_format::fixed, "-nan"},
    {2.018f, str::float_format::fixed, 3, "2.018"},
    {-2.018f, str::float_format::fixed, 3, "-2.018"},

    // Ditto for general, which selects fixed for the scientific exponent 0.
    {0.0f, str::float_format::general, "0.000000"},
    {-0.0f, str::float_format::general, "-0.000000"},
    {float_inf, str::float_format::general, "inf"},
    {-float_inf, str::float_format::general, "-inf"},
    {float_nan, str::float_format::general, "nan"},
    {-float_nan, str::float_format::general, "-nan(ind)"},
    {float_nan_payload, str::float_format::general, "nan"},
    {-float_nan_payload, str::float_format::general, "-nan"},
    {2.018f, str::float_format::general, "2.018000"},
    {-2.018f, str::float_format::general, "-2.018000"},

    // Ditto for hex.
    {0.0f, str::float_format::hex, 0, "0p0"},
    {-0.0f, str::float_format::hex, 0, "-0p0"},
    {float_inf, str::float_format::hex, "inf"},
    {-float_inf, str::float_format::hex, "-inf"},
    {float_nan, str::float_format::hex, "nan"},
    {-float_nan, str::float_format::hex, "-nan(ind)"},
    {float_nan_payload, str::float_format::hex, "nan"},
    {-float_nan_payload, str::float_format::hex, "-nan"},
    {0x1.729p+0f, str::float_format::hex, 3, "1.729p0"},
    {-0x1.729p+0f, str::float_format::hex, 3, "-1.729p0"}
};

// clang-format on
