#pragma once

#include <cstdint>

#include "vertex/config/util.hpp"
#include "vertex/config/flags.hpp"
#include "vertex/app/input/scancode.hpp"

namespace vx {
namespace app {
namespace keyboard {

namespace _priv {

enum : uint32_t
{
    extended_mask = VX_BIT(29),
    scancode_mask = VX_BIT(30)
};

} // namespace _priv

#define MAKE_EXTENDED_KEYCODE(i) (i | _priv::extended_mask)
#define MAKE_KEYCODE(sc) (sc | _priv::scancode_mask)

enum keycode : uint32_t
{
    key_unknown                 = 0,
    
    key_return                  = '\r',
    key_backspace               = '\b',
    key_tab                     = '\t',
    key_escape                  = 0x0000001Bu,
    key_space                   = ' ',
    key_exclaim                 = '!',
    key_dblapostrophe           = '"',
    key_hash                    = '#',
    key_dollar                  = '$',
    key_percent                 = '%',
    key_ampersand               = '&',
    key_apostrophe              = '\'',
    key_leftparen               = '(',
    key_rightparen              = ')',
    key_asterisk                = '*',
    key_plus                    = '+',
    key_comma                   = ',',
    key_minus                   = '-',
    key_period                  = '.',
    key_slash                   = '/',
    key_0                       = '0',
    key_1                       = '1',
    key_2                       = '2',
    key_3                       = '3',
    key_4                       = '4',
    key_5                       = '5',
    key_6                       = '6',
    key_7                       = '7',
    key_8                       = '8',
    key_9                       = '9',
    key_colon                   = ':',
    key_semicolon               = ';',
    key_less                    = '<',
    key_equals                  = '=',
    key_greater                 = '>',
    key_question                = '?',
    key_at                      = '@',
    key_leftbracket             = '[',
    key_backslash               = '\\',
    key_rightbracket            = ']',
    key_caret                   = '^',
    key_underscore              = '_',
    key_grave                   = '`',
    key_a                       = 'a',
    key_b                       = 'b',
    key_c                       = 'c',
    key_d                       = 'd',
    key_e                       = 'e',
    key_f                       = 'f',
    key_g                       = 'g',
    key_h                       = 'h',
    key_i                       = 'i',
    key_j                       = 'j',
    key_k                       = 'k',
    key_l                       = 'l',
    key_m                       = 'm',
    key_n                       = 'n',
    key_o                       = 'o',
    key_p                       = 'p',
    key_q                       = 'q',
    key_r                       = 'r',
    key_s                       = 's',
    key_t                       = 't',
    key_u                       = 'u',
    key_v                       = 'v',
    key_w                       = 'w',
    key_x                       = 'x',
    key_y                       = 'y',
    key_z                       = 'z',
    key_leftbrace               = '{',
    key_pipe                    = '|',
    key_rightbrace              = '}',
    key_tilde                   = '~',
    key_delete                  = 0x0000007Fu,
    key_plusminus               = 0x000000B1u,

    key_capslock                = MAKE_KEYCODE(scancode_capslock),
    key_f1                      = MAKE_KEYCODE(scancode_f1),
    key_f2                      = MAKE_KEYCODE(scancode_f2),
    key_f3                      = MAKE_KEYCODE(scancode_f3),
    key_f4                      = MAKE_KEYCODE(scancode_f4),
    key_f5                      = MAKE_KEYCODE(scancode_f5),
    key_f6                      = MAKE_KEYCODE(scancode_f6),
    key_f7                      = MAKE_KEYCODE(scancode_f7),
    key_f8                      = MAKE_KEYCODE(scancode_f8),
    key_f9                      = MAKE_KEYCODE(scancode_f9),
    key_f10                     = MAKE_KEYCODE(scancode_f10),
    key_f11                     = MAKE_KEYCODE(scancode_f11),
    key_f12                     = MAKE_KEYCODE(scancode_f12),
    key_printscreen             = MAKE_KEYCODE(scancode_printscreen),
    key_scrolllock              = MAKE_KEYCODE(scancode_scrolllock),
    key_pause                   = MAKE_KEYCODE(scancode_pause),
    key_insert                  = MAKE_KEYCODE(scancode_insert),
    key_home                    = MAKE_KEYCODE(scancode_home),
    key_pageup                  = MAKE_KEYCODE(scancode_pageup),
    key_end                     = MAKE_KEYCODE(scancode_end),
    key_pagedown                = MAKE_KEYCODE(scancode_pagedown),
    key_right                   = MAKE_KEYCODE(scancode_right),
    key_left                    = MAKE_KEYCODE(scancode_left),
    key_down                    = MAKE_KEYCODE(scancode_down),
    key_up                      = MAKE_KEYCODE(scancode_up),
    key_numlock_clear           = MAKE_KEYCODE(scancode_numlock_clear),
    key_kp_divide               = MAKE_KEYCODE(scancode_kp_divide),
    key_kp_multiply             = MAKE_KEYCODE(scancode_kp_multiply),
    key_kp_minus                = MAKE_KEYCODE(scancode_kp_minus),
    key_kp_plus                 = MAKE_KEYCODE(scancode_kp_plus),
    key_kp_enter                = MAKE_KEYCODE(scancode_kp_enter),
    key_kp_1                    = MAKE_KEYCODE(scancode_kp_1),
    key_kp_2                    = MAKE_KEYCODE(scancode_kp_2),
    key_kp_3                    = MAKE_KEYCODE(scancode_kp_3),
    key_kp_4                    = MAKE_KEYCODE(scancode_kp_4),
    key_kp_5                    = MAKE_KEYCODE(scancode_kp_5),
    key_kp_6                    = MAKE_KEYCODE(scancode_kp_6),
    key_kp_7                    = MAKE_KEYCODE(scancode_kp_7),
    key_kp_8                    = MAKE_KEYCODE(scancode_kp_8),
    key_kp_9                    = MAKE_KEYCODE(scancode_kp_9),
    key_kp_0                    = MAKE_KEYCODE(scancode_kp_0),
    key_kp_period               = MAKE_KEYCODE(scancode_kp_period),
    key_application             = MAKE_KEYCODE(scancode_application),
    key_power                   = MAKE_KEYCODE(scancode_power),
    key_kp_equals               = MAKE_KEYCODE(scancode_kp_equals),
    key_f13                     = MAKE_KEYCODE(scancode_f13),
    key_f14                     = MAKE_KEYCODE(scancode_f14),
    key_f15                     = MAKE_KEYCODE(scancode_f15),
    key_f16                     = MAKE_KEYCODE(scancode_f16),
    key_f17                     = MAKE_KEYCODE(scancode_f17),
    key_f18                     = MAKE_KEYCODE(scancode_f18),
    key_f19                     = MAKE_KEYCODE(scancode_f19),
    key_f20                     = MAKE_KEYCODE(scancode_f20),
    key_f21                     = MAKE_KEYCODE(scancode_f21),
    key_f22                     = MAKE_KEYCODE(scancode_f22),
    key_f23                     = MAKE_KEYCODE(scancode_f23),
    key_f24                     = MAKE_KEYCODE(scancode_f24),
    key_execute                 = MAKE_KEYCODE(scancode_execute),
    key_help                    = MAKE_KEYCODE(scancode_help),
    key_menu                    = MAKE_KEYCODE(scancode_menu),
    key_select                  = MAKE_KEYCODE(scancode_select),
    key_stop                    = MAKE_KEYCODE(scancode_stop),
    key_again                   = MAKE_KEYCODE(scancode_again),
    key_undo                    = MAKE_KEYCODE(scancode_undo),
    key_cut                     = MAKE_KEYCODE(scancode_cut),
    key_copy                    = MAKE_KEYCODE(scancode_copy),
    key_paste                   = MAKE_KEYCODE(scancode_paste),
    key_find                    = MAKE_KEYCODE(scancode_find),
    key_mute                    = MAKE_KEYCODE(scancode_mute),
    key_volumeup                = MAKE_KEYCODE(scancode_volumeup),
    key_volumedown              = MAKE_KEYCODE(scancode_volumedown),
    key_kp_comma                = MAKE_KEYCODE(scancode_kp_comma),
    key_kp_equalsas400          = MAKE_KEYCODE(scancode_kp_equalsas400),
    key_alterase                = MAKE_KEYCODE(scancode_alterase),
    key_sysreq                  = MAKE_KEYCODE(scancode_sysreq),
    key_cancel                  = MAKE_KEYCODE(scancode_cancel),
    key_clear                   = MAKE_KEYCODE(scancode_clear),
    key_prior                   = MAKE_KEYCODE(scancode_prior),
    key_return2                 = MAKE_KEYCODE(scancode_return2),
    key_separator               = MAKE_KEYCODE(scancode_separator),
    key_out                     = MAKE_KEYCODE(scancode_out),
    key_oper                    = MAKE_KEYCODE(scancode_oper),
    key_clearagain              = MAKE_KEYCODE(scancode_clearagain),
    key_crsel                   = MAKE_KEYCODE(scancode_crsel),
    key_exsel                   = MAKE_KEYCODE(scancode_exsel),
    key_kp_00                   = MAKE_KEYCODE(scancode_kp_00),
    key_kp_000                  = MAKE_KEYCODE(scancode_kp_000),
    key_thousandsseparatoR      = MAKE_KEYCODE(scancode_thousandsseparator),
    key_decimalseparator        = MAKE_KEYCODE(scancode_decimalseparator),
    key_currencyunit            = MAKE_KEYCODE(scancode_currencyunit),
    key_currencysubunit         = MAKE_KEYCODE(scancode_currencysubunit),
    key_kp_leftparen            = MAKE_KEYCODE(scancode_kp_leftparen),
    key_kp_rightparen           = MAKE_KEYCODE(scancode_kp_rightparen),
    key_kp_leftbrace            = MAKE_KEYCODE(scancode_kp_leftbrace),
    key_kp_rightbrace           = MAKE_KEYCODE(scancode_kp_rightbrace),
    key_kp_tab                  = MAKE_KEYCODE(scancode_kp_tab),
    key_kp_backspace            = MAKE_KEYCODE(scancode_kp_backspace),
    key_kp_a                    = MAKE_KEYCODE(scancode_kp_a),
    key_kp_b                    = MAKE_KEYCODE(scancode_kp_b),
    key_kp_c                    = MAKE_KEYCODE(scancode_kp_c),
    key_kp_d                    = MAKE_KEYCODE(scancode_kp_d),
    key_kp_e                    = MAKE_KEYCODE(scancode_kp_e),
    key_kp_f                    = MAKE_KEYCODE(scancode_kp_f),
    key_kp_xor                  = MAKE_KEYCODE(scancode_kp_xor),
    key_kp_power                = MAKE_KEYCODE(scancode_kp_power),
    key_kp_percent              = MAKE_KEYCODE(scancode_kp_percent),
    key_kp_less                 = MAKE_KEYCODE(scancode_kp_less),
    key_kp_greater              = MAKE_KEYCODE(scancode_kp_greater),
    key_kp_ampersand            = MAKE_KEYCODE(scancode_kp_ampersand),
    key_kp_dblampersand         = MAKE_KEYCODE(scancode_kp_dblampersand),
    key_kp_verticalbar          = MAKE_KEYCODE(scancode_kp_verticalbar),
    key_kp_dblverticalbar       = MAKE_KEYCODE(scancode_kp_dblverticalbar),
    key_kp_colon                = MAKE_KEYCODE(scancode_kp_colon),
    key_kp_hash                 = MAKE_KEYCODE(scancode_kp_hash),
    key_kp_space                = MAKE_KEYCODE(scancode_kp_space),
    key_kp_at                   = MAKE_KEYCODE(scancode_kp_at),
    key_kp_exclam               = MAKE_KEYCODE(scancode_kp_exclam),
    key_kp_memstore             = MAKE_KEYCODE(scancode_kp_memstore),
    key_kp_memrecall            = MAKE_KEYCODE(scancode_kp_memrecall),
    key_kp_memclear             = MAKE_KEYCODE(scancode_kp_memclear),
    key_kp_memadd               = MAKE_KEYCODE(scancode_kp_memadd),
    key_kp_memsubtract          = MAKE_KEYCODE(scancode_kp_memsubtract),
    key_kp_memmultiply          = MAKE_KEYCODE(scancode_kp_memmultiply),
    key_kp_memdivide            = MAKE_KEYCODE(scancode_kp_memdivide),
    key_kp_plusminus            = MAKE_KEYCODE(scancode_kp_plusminus),
    key_kp_clear                = MAKE_KEYCODE(scancode_kp_clear),
    key_kp_clearentry           = MAKE_KEYCODE(scancode_kp_clearentry),
    key_kp_binary               = MAKE_KEYCODE(scancode_kp_binary),
    key_kp_octal                = MAKE_KEYCODE(scancode_kp_octal),
    key_kp_decimal              = MAKE_KEYCODE(scancode_kp_decimal),
    key_kp_hexadecimal          = MAKE_KEYCODE(scancode_kp_hexadecimal),
    key_lctrl                   = MAKE_KEYCODE(scancode_lctrl),
    key_lshift                  = MAKE_KEYCODE(scancode_lshift),
    key_lalt                    = MAKE_KEYCODE(scancode_lalt),
    key_lgui                    = MAKE_KEYCODE(scancode_lgui),
    key_rctrl                   = MAKE_KEYCODE(scancode_rctrl),
    key_rshift                  = MAKE_KEYCODE(scancode_rshift),
    key_ralt                    = MAKE_KEYCODE(scancode_ralt),
    key_rgui                    = MAKE_KEYCODE(scancode_rgui),
    key_mode                    = MAKE_KEYCODE(scancode_mode),
    key_sleep                   = MAKE_KEYCODE(scancode_sleep),
    key_wake                    = MAKE_KEYCODE(scancode_wake),
    key_channel_increment       = MAKE_KEYCODE(scancode_channel_increment),
    key_channel_decrement       = MAKE_KEYCODE(scancode_channel_decrement),
    key_media_play              = MAKE_KEYCODE(scancode_media_play),
    key_media_pause             = MAKE_KEYCODE(scancode_media_pause),
    key_media_record            = MAKE_KEYCODE(scancode_media_record),
    key_media_fast_forwarD      = MAKE_KEYCODE(scancode_media_fast_forward),
    key_media_rewind            = MAKE_KEYCODE(scancode_media_rewind),
    key_media_next_track        = MAKE_KEYCODE(scancode_media_next_track),
    key_media_previous_trACK    = MAKE_KEYCODE(scancode_media_previous_track),
    key_media_stop              = MAKE_KEYCODE(scancode_media_stop),
    key_media_eject             = MAKE_KEYCODE(scancode_media_eject),
    key_media_play_pause        = MAKE_KEYCODE(scancode_media_play_pause),
    key_media_select            = MAKE_KEYCODE(scancode_media_select),
    key_ac_new                  = MAKE_KEYCODE(scancode_ac_new),
    key_ac_open                 = MAKE_KEYCODE(scancode_ac_open),
    key_ac_close                = MAKE_KEYCODE(scancode_ac_close),
    key_ac_exit                 = MAKE_KEYCODE(scancode_ac_exit),
    key_ac_save                 = MAKE_KEYCODE(scancode_ac_save),
    key_ac_print                = MAKE_KEYCODE(scancode_ac_print),
    key_ac_properties           = MAKE_KEYCODE(scancode_ac_properties),
    key_ac_search               = MAKE_KEYCODE(scancode_ac_search),
    key_ac_home                 = MAKE_KEYCODE(scancode_ac_home),
    key_ac_back                 = MAKE_KEYCODE(scancode_ac_back),
    key_ac_forward              = MAKE_KEYCODE(scancode_ac_forward),
    key_ac_stop                 = MAKE_KEYCODE(scancode_ac_stop),
    key_ac_refresh              = MAKE_KEYCODE(scancode_ac_refresh),
    key_ac_bookmarks            = MAKE_KEYCODE(scancode_ac_bookmarks),
    key_softleft                = MAKE_KEYCODE(scancode_softleft),
    key_softright               = MAKE_KEYCODE(scancode_softright),
    key_call                    = MAKE_KEYCODE(scancode_call),
    key_endcall                 = MAKE_KEYCODE(scancode_endcall),

    key_left_tab                = MAKE_EXTENDED_KEYCODE(1),
    key_level5_shift            = MAKE_EXTENDED_KEYCODE(2),
    key_multi_key_compose       = MAKE_EXTENDED_KEYCODE(3),
    key_lmeta                   = MAKE_EXTENDED_KEYCODE(4),
    key_rmeta                   = MAKE_EXTENDED_KEYCODE(5),
    key_lhyper                  = MAKE_EXTENDED_KEYCODE(6),
    key_rhyper                  = MAKE_EXTENDED_KEYCODE(7)
};

#undef MAKE_EXTENDED_KEYCODE
#undef MAKE_KEYCODE

VX_FLAGS_UT_DECLARE_BEGIN(key_mod, uint16_t)
{
    none   = 0x0000,

    lshift = 0x0001,
    rshift = 0x0002,
    shift  = (lshift | rshift),

    lctrl  = 0x0040,
    rctrl  = 0x0080,
    ctrl   = (lctrl | rctrl),

    lalt   = 0x0100,
    ralt   = 0x0200,
    alt    = (lalt | ralt),

    lgui   = 0x0400,
    rgui   = 0x0800,
    gui    = (lgui | rgui),

    num    = 0x1000,
    caps   = 0x2000,
    mode   = 0x4000,
    scroll = 0x8000
}
VX_FLAGS_DECLARE_END(key_mod)

} // namespace keyboard
} // namespace app
} // namespace vx