#pragma once

#include <cstdint>

#include "vertex/app/input/scancode.hpp"

namespace vx {
namespace app {
namespace keyboard {

namespace _priv {

enum : uint32_t
{
    EXTENDED_MASK = (1u << 29),
    SCANCODE_MASK = (1u << 30)
};

} // namespace _priv

#define MAKE_EXTENDED_KEYCODE(i) (i | _priv::EXTENDED_MASK)
#define MAKE_KEYCODE(sc) (sc | _priv::SCANCODE_MASK)

enum keycode : uint32_t
{
    KEY_UNKNOWN                 = 0,
    
    KEY_RETURN                  = '\r',
    KEY_BACKSPACE               = '\b',
    KEY_TAB                     = '\t',
    KEY_ESCAPE                  = 0x0000001Bu,
    KEY_SPACE                   = ' ',
    KEY_EXCLAIM                 = '!',
    KEY_DBLAPOSTROPHE           = '"',
    KEY_HASH                    = '#',
    KEY_DOLLAR                  = '$',
    KEY_PERCENT                 = '%',
    KEY_AMPERSAND               = '&',
    KEY_APOSTROPHE              = '\'',
    KEY_LEFTPAREN               = '(',
    KEY_RIGHTPAREN              = ')',
    KEY_ASTERISK                = '*',
    KEY_PLUS                    = '+',
    KEY_COMMA                   = ',',
    KEY_MINUS                   = '-',
    KEY_PERIOD                  = '.',
    KEY_SLASH                   = '/',
    KEY_0                       = '0',
    KEY_1                       = '1',
    KEY_2                       = '2',
    KEY_3                       = '3',
    KEY_4                       = '4',
    KEY_5                       = '5',
    KEY_6                       = '6',
    KEY_7                       = '7',
    KEY_8                       = '8',
    KEY_9                       = '9',
    KEY_COLON                   = ':',
    KEY_SEMICOLON               = ';',
    KEY_LESS                    = '<',
    KEY_EQUALS                  = '=',
    KEY_GREATER                 = '>',
    KEY_QUESTION                = '?',
    KEY_AT                      = '@',
    KEY_LEFTBRACKET             = '[',
    KEY_BACKSLASH               = '\\',
    KEY_RIGHTBRACKET            = ']',
    KEY_CARET                   = '^',
    KEY_UNDERSCORE              = '_',
    KEY_GRAVE                   = '`',
    KEY_A                       = 'a',
    KEY_B                       = 'b',
    KEY_C                       = 'c',
    KEY_D                       = 'd',
    KEY_E                       = 'e',
    KEY_F                       = 'f',
    KEY_G                       = 'g',
    KEY_H                       = 'h',
    KEY_I                       = 'i',
    KEY_J                       = 'j',
    KEY_K                       = 'k',
    KEY_L                       = 'l',
    KEY_M                       = 'm',
    KEY_N                       = 'n',
    KEY_O                       = 'o',
    KEY_P                       = 'p',
    KEY_Q                       = 'q',
    KEY_R                       = 'r',
    KEY_S                       = 's',
    KEY_T                       = 't',
    KEY_U                       = 'u',
    KEY_V                       = 'v',
    KEY_W                       = 'w',
    KEY_X                       = 'x',
    KEY_Y                       = 'y',
    KEY_Z                       = 'z',
    KEY_LEFTBRACE               = '{',
    KEY_PIPE                    = '|',
    KEY_RIGHTBRACE              = '}',
    KEY_TILDE                   = '~',
    KEY_DELETE                  = 0x0000007Fu,
    KEY_PLUSMINUS               = 0x000000B1u,

    KEY_CAPSLOCK                = MAKE_KEYCODE(SCANCODE_CAPSLOCK),
    KEY_F1                      = MAKE_KEYCODE(SCANCODE_F1),
    KEY_F2                      = MAKE_KEYCODE(SCANCODE_F2),
    KEY_F3                      = MAKE_KEYCODE(SCANCODE_F3),
    KEY_F4                      = MAKE_KEYCODE(SCANCODE_F4),
    KEY_F5                      = MAKE_KEYCODE(SCANCODE_F5),
    KEY_F6                      = MAKE_KEYCODE(SCANCODE_F6),
    KEY_F7                      = MAKE_KEYCODE(SCANCODE_F7),
    KEY_F8                      = MAKE_KEYCODE(SCANCODE_F8),
    KEY_F9                      = MAKE_KEYCODE(SCANCODE_F9),
    KEY_F10                     = MAKE_KEYCODE(SCANCODE_F10),
    KEY_F11                     = MAKE_KEYCODE(SCANCODE_F11),
    KEY_F12                     = MAKE_KEYCODE(SCANCODE_F12),
    KEY_PRINTSCREEN             = MAKE_KEYCODE(SCANCODE_PRINTSCREEN),
    KEY_SCROLLLOCK              = MAKE_KEYCODE(SCANCODE_SCROLLLOCK),
    KEY_PAUSE                   = MAKE_KEYCODE(SCANCODE_PAUSE),
    KEY_INSERT                  = MAKE_KEYCODE(SCANCODE_INSERT),
    KEY_HOME                    = MAKE_KEYCODE(SCANCODE_HOME),
    KEY_PAGEUP                  = MAKE_KEYCODE(SCANCODE_PAGEUP),
    KEY_END                     = MAKE_KEYCODE(SCANCODE_END),
    KEY_PAGEDOWN                = MAKE_KEYCODE(SCANCODE_PAGEDOWN),
    KEY_RIGHT                   = MAKE_KEYCODE(SCANCODE_RIGHT),
    KEY_LEFT                    = MAKE_KEYCODE(SCANCODE_LEFT),
    KEY_DOWN                    = MAKE_KEYCODE(SCANCODE_DOWN),
    KEY_UP                      = MAKE_KEYCODE(SCANCODE_UP),
    KEY_NUMLOCK_CLEAR           = MAKE_KEYCODE(SCANCODE_NUMLOCK_CLEAR),
    KEY_KP_DIVIDE               = MAKE_KEYCODE(SCANCODE_KP_DIVIDE),
    KEY_KP_MULTIPLY             = MAKE_KEYCODE(SCANCODE_KP_MULTIPLY),
    KEY_KP_MINUS                = MAKE_KEYCODE(SCANCODE_KP_MINUS),
    KEY_KP_PLUS                 = MAKE_KEYCODE(SCANCODE_KP_PLUS),
    KEY_KP_ENTER                = MAKE_KEYCODE(SCANCODE_KP_ENTER),
    KEY_KP_1                    = MAKE_KEYCODE(SCANCODE_KP_1),
    KEY_KP_2                    = MAKE_KEYCODE(SCANCODE_KP_2),
    KEY_KP_3                    = MAKE_KEYCODE(SCANCODE_KP_3),
    KEY_KP_4                    = MAKE_KEYCODE(SCANCODE_KP_4),
    KEY_KP_5                    = MAKE_KEYCODE(SCANCODE_KP_5),
    KEY_KP_6                    = MAKE_KEYCODE(SCANCODE_KP_6),
    KEY_KP_7                    = MAKE_KEYCODE(SCANCODE_KP_7),
    KEY_KP_8                    = MAKE_KEYCODE(SCANCODE_KP_8),
    KEY_KP_9                    = MAKE_KEYCODE(SCANCODE_KP_9),
    KEY_KP_0                    = MAKE_KEYCODE(SCANCODE_KP_0),
    KEY_KP_PERIOD               = MAKE_KEYCODE(SCANCODE_KP_PERIOD),
    KEY_APPLICATION             = MAKE_KEYCODE(SCANCODE_APPLICATION),
    KEY_POWER                   = MAKE_KEYCODE(SCANCODE_POWER),
    KEY_KP_EQUALS               = MAKE_KEYCODE(SCANCODE_KP_EQUALS),
    KEY_F13                     = MAKE_KEYCODE(SCANCODE_F13),
    KEY_F14                     = MAKE_KEYCODE(SCANCODE_F14),
    KEY_F15                     = MAKE_KEYCODE(SCANCODE_F15),
    KEY_F16                     = MAKE_KEYCODE(SCANCODE_F16),
    KEY_F17                     = MAKE_KEYCODE(SCANCODE_F17),
    KEY_F18                     = MAKE_KEYCODE(SCANCODE_F18),
    KEY_F19                     = MAKE_KEYCODE(SCANCODE_F19),
    KEY_F20                     = MAKE_KEYCODE(SCANCODE_F20),
    KEY_F21                     = MAKE_KEYCODE(SCANCODE_F21),
    KEY_F22                     = MAKE_KEYCODE(SCANCODE_F22),
    KEY_F23                     = MAKE_KEYCODE(SCANCODE_F23),
    KEY_F24                     = MAKE_KEYCODE(SCANCODE_F24),
    KEY_EXECUTE                 = MAKE_KEYCODE(SCANCODE_EXECUTE),
    KEY_HELP                    = MAKE_KEYCODE(SCANCODE_HELP),
    KEY_MENU                    = MAKE_KEYCODE(SCANCODE_MENU),
    KEY_SELECT                  = MAKE_KEYCODE(SCANCODE_SELECT),
    KEY_STOP                    = MAKE_KEYCODE(SCANCODE_STOP),
    KEY_AGAIN                   = MAKE_KEYCODE(SCANCODE_AGAIN),
    KEY_UNDO                    = MAKE_KEYCODE(SCANCODE_UNDO),
    KEY_CUT                     = MAKE_KEYCODE(SCANCODE_CUT),
    KEY_COPY                    = MAKE_KEYCODE(SCANCODE_COPY),
    KEY_PASTE                   = MAKE_KEYCODE(SCANCODE_PASTE),
    KEY_FIND                    = MAKE_KEYCODE(SCANCODE_FIND),
    KEY_MUTE                    = MAKE_KEYCODE(SCANCODE_MUTE),
    KEY_VOLUMEUP                = MAKE_KEYCODE(SCANCODE_VOLUMEUP),
    KEY_VOLUMEDOWN              = MAKE_KEYCODE(SCANCODE_VOLUMEDOWN),
    KEY_KP_COMMA                = MAKE_KEYCODE(SCANCODE_KP_COMMA),
    KEY_KP_EQUALSAS400          = MAKE_KEYCODE(SCANCODE_KP_EQUALSAS400),
    KEY_ALTERASE                = MAKE_KEYCODE(SCANCODE_ALTERASE),
    KEY_SYSREQ                  = MAKE_KEYCODE(SCANCODE_SYSREQ),
    KEY_CANCEL                  = MAKE_KEYCODE(SCANCODE_CANCEL),
    KEY_CLEAR                   = MAKE_KEYCODE(SCANCODE_CLEAR),
    KEY_PRIOR                   = MAKE_KEYCODE(SCANCODE_PRIOR),
    KEY_RETURN2                 = MAKE_KEYCODE(SCANCODE_RETURN2),
    KEY_SEPARATOR               = MAKE_KEYCODE(SCANCODE_SEPARATOR),
    KEY_OUT                     = MAKE_KEYCODE(SCANCODE_OUT),
    KEY_OPER                    = MAKE_KEYCODE(SCANCODE_OPER),
    KEY_CLEARAGAIN              = MAKE_KEYCODE(SCANCODE_CLEARAGAIN),
    KEY_CRSEL                   = MAKE_KEYCODE(SCANCODE_CRSEL),
    KEY_EXSEL                   = MAKE_KEYCODE(SCANCODE_EXSEL),
    KEY_KP_00                   = MAKE_KEYCODE(SCANCODE_KP_00),
    KEY_KP_000                  = MAKE_KEYCODE(SCANCODE_KP_000),
    KEY_THOUSANDSSEPARATOR      = MAKE_KEYCODE(SCANCODE_THOUSANDSSEPARATOR),
    KEY_DECIMALSEPARATOR        = MAKE_KEYCODE(SCANCODE_DECIMALSEPARATOR),
    KEY_CURRENCYUNIT            = MAKE_KEYCODE(SCANCODE_CURRENCYUNIT),
    KEY_CURRENCYSUBUNIT         = MAKE_KEYCODE(SCANCODE_CURRENCYSUBUNIT),
    KEY_KP_LEFTPAREN            = MAKE_KEYCODE(SCANCODE_KP_LEFTPAREN),
    KEY_KP_RIGHTPAREN           = MAKE_KEYCODE(SCANCODE_KP_RIGHTPAREN),
    KEY_KP_LEFTBRACE            = MAKE_KEYCODE(SCANCODE_KP_LEFTBRACE),
    KEY_KP_RIGHTBRACE           = MAKE_KEYCODE(SCANCODE_KP_RIGHTBRACE),
    KEY_KP_TAB                  = MAKE_KEYCODE(SCANCODE_KP_TAB),
    KEY_KP_BACKSPACE            = MAKE_KEYCODE(SCANCODE_KP_BACKSPACE),
    KEY_KP_A                    = MAKE_KEYCODE(SCANCODE_KP_A),
    KEY_KP_B                    = MAKE_KEYCODE(SCANCODE_KP_B),
    KEY_KP_C                    = MAKE_KEYCODE(SCANCODE_KP_C),
    KEY_KP_D                    = MAKE_KEYCODE(SCANCODE_KP_D),
    KEY_KP_E                    = MAKE_KEYCODE(SCANCODE_KP_E),
    KEY_KP_F                    = MAKE_KEYCODE(SCANCODE_KP_F),
    KEY_KP_XOR                  = MAKE_KEYCODE(SCANCODE_KP_XOR),
    KEY_KP_POWER                = MAKE_KEYCODE(SCANCODE_KP_POWER),
    KEY_KP_PERCENT              = MAKE_KEYCODE(SCANCODE_KP_PERCENT),
    KEY_KP_LESS                 = MAKE_KEYCODE(SCANCODE_KP_LESS),
    KEY_KP_GREATER              = MAKE_KEYCODE(SCANCODE_KP_GREATER),
    KEY_KP_AMPERSAND            = MAKE_KEYCODE(SCANCODE_KP_AMPERSAND),
    KEY_KP_DBLAMPERSAND         = MAKE_KEYCODE(SCANCODE_KP_DBLAMPERSAND),
    KEY_KP_VERTICALBAR          = MAKE_KEYCODE(SCANCODE_KP_VERTICALBAR),
    KEY_KP_DBLVERTICALBAR       = MAKE_KEYCODE(SCANCODE_KP_DBLVERTICALBAR),
    KEY_KP_COLON                = MAKE_KEYCODE(SCANCODE_KP_COLON),
    KEY_KP_HASH                 = MAKE_KEYCODE(SCANCODE_KP_HASH),
    KEY_KP_SPACE                = MAKE_KEYCODE(SCANCODE_KP_SPACE),
    KEY_KP_AT                   = MAKE_KEYCODE(SCANCODE_KP_AT),
    KEY_KP_EXCLAM               = MAKE_KEYCODE(SCANCODE_KP_EXCLAM),
    KEY_KP_MEMSTORE             = MAKE_KEYCODE(SCANCODE_KP_MEMSTORE),
    KEY_KP_MEMRECALL            = MAKE_KEYCODE(SCANCODE_KP_MEMRECALL),
    KEY_KP_MEMCLEAR             = MAKE_KEYCODE(SCANCODE_KP_MEMCLEAR),
    KEY_KP_MEMADD               = MAKE_KEYCODE(SCANCODE_KP_MEMADD),
    KEY_KP_MEMSUBTRACT          = MAKE_KEYCODE(SCANCODE_KP_MEMSUBTRACT),
    KEY_KP_MEMMULTIPLY          = MAKE_KEYCODE(SCANCODE_KP_MEMMULTIPLY),
    KEY_KP_MEMDIVIDE            = MAKE_KEYCODE(SCANCODE_KP_MEMDIVIDE),
    KEY_KP_PLUSMINUS            = MAKE_KEYCODE(SCANCODE_KP_PLUSMINUS),
    KEY_KP_CLEAR                = MAKE_KEYCODE(SCANCODE_KP_CLEAR),
    KEY_KP_CLEARENTRY           = MAKE_KEYCODE(SCANCODE_KP_CLEARENTRY),
    KEY_KP_BINARY               = MAKE_KEYCODE(SCANCODE_KP_BINARY),
    KEY_KP_OCTAL                = MAKE_KEYCODE(SCANCODE_KP_OCTAL),
    KEY_KP_DECIMAL              = MAKE_KEYCODE(SCANCODE_KP_DECIMAL),
    KEY_KP_HEXADECIMAL          = MAKE_KEYCODE(SCANCODE_KP_HEXADECIMAL),
    KEY_LCTRL                   = MAKE_KEYCODE(SCANCODE_LCTRL),
    KEY_LSHIFT                  = MAKE_KEYCODE(SCANCODE_LSHIFT),
    KEY_LALT                    = MAKE_KEYCODE(SCANCODE_LALT),
    KEY_LGUI                    = MAKE_KEYCODE(SCANCODE_LGUI),
    KEY_RCTRL                   = MAKE_KEYCODE(SCANCODE_RCTRL),
    KEY_RSHIFT                  = MAKE_KEYCODE(SCANCODE_RSHIFT),
    KEY_RALT                    = MAKE_KEYCODE(SCANCODE_RALT),
    KEY_RGUI                    = MAKE_KEYCODE(SCANCODE_RGUI),
    MODE                    = MAKE_KEYCODE(SCANCODE_MODE),
    KEY_SLEEP                   = MAKE_KEYCODE(SCANCODE_SLEEP),
    KEY_WAKE                    = MAKE_KEYCODE(SCANCODE_WAKE),
    KEY_CHANNEL_INCREMENT       = MAKE_KEYCODE(SCANCODE_CHANNEL_INCREMENT),
    KEY_CHANNEL_DECREMENT       = MAKE_KEYCODE(SCANCODE_CHANNEL_DECREMENT),
    KEY_MEDIA_PLAY              = MAKE_KEYCODE(SCANCODE_MEDIA_PLAY),
    KEY_MEDIA_PAUSE             = MAKE_KEYCODE(SCANCODE_MEDIA_PAUSE),
    KEY_MEDIA_RECORD            = MAKE_KEYCODE(SCANCODE_MEDIA_RECORD),
    KEY_MEDIA_FAST_FORWARD      = MAKE_KEYCODE(SCANCODE_MEDIA_FAST_FORWARD),
    KEY_MEDIA_REWIND            = MAKE_KEYCODE(SCANCODE_MEDIA_REWIND),
    KEY_MEDIA_NEXT_TRACK        = MAKE_KEYCODE(SCANCODE_MEDIA_NEXT_TRACK),
    KEY_MEDIA_PREVIOUS_TRACK    = MAKE_KEYCODE(SCANCODE_MEDIA_PREVIOUS_TRACK),
    KEY_MEDIA_STOP              = MAKE_KEYCODE(SCANCODE_MEDIA_STOP),
    KEY_MEDIA_EJECT             = MAKE_KEYCODE(SCANCODE_MEDIA_EJECT),
    KEY_MEDIA_PLAY_PAUSE        = MAKE_KEYCODE(SCANCODE_MEDIA_PLAY_PAUSE),
    KEY_MEDIA_SELECT            = MAKE_KEYCODE(SCANCODE_MEDIA_SELECT),
    KEY_AC_NEW                  = MAKE_KEYCODE(SCANCODE_AC_NEW),
    KEY_AC_OPEN                 = MAKE_KEYCODE(SCANCODE_AC_OPEN),
    KEY_AC_CLOSE                = MAKE_KEYCODE(SCANCODE_AC_CLOSE),
    KEY_AC_EXIT                 = MAKE_KEYCODE(SCANCODE_AC_EXIT),
    KEY_AC_SAVE                 = MAKE_KEYCODE(SCANCODE_AC_SAVE),
    KEY_AC_PRINT                = MAKE_KEYCODE(SCANCODE_AC_PRINT),
    KEY_AC_PROPERTIES           = MAKE_KEYCODE(SCANCODE_AC_PROPERTIES),
    KEY_AC_SEARCH               = MAKE_KEYCODE(SCANCODE_AC_SEARCH),
    KEY_AC_HOME                 = MAKE_KEYCODE(SCANCODE_AC_HOME),
    KEY_AC_BACK                 = MAKE_KEYCODE(SCANCODE_AC_BACK),
    KEY_AC_FORWARD              = MAKE_KEYCODE(SCANCODE_AC_FORWARD),
    KEY_AC_STOP                 = MAKE_KEYCODE(SCANCODE_AC_STOP),
    KEY_AC_REFRESH              = MAKE_KEYCODE(SCANCODE_AC_REFRESH),
    KEY_AC_BOOKMARKS            = MAKE_KEYCODE(SCANCODE_AC_BOOKMARKS),
    KEY_SOFTLEFT                = MAKE_KEYCODE(SCANCODE_SOFTLEFT),
    KEY_SOFTRIGHT               = MAKE_KEYCODE(SCANCODE_SOFTRIGHT),
    KEY_CALL                    = MAKE_KEYCODE(SCANCODE_CALL),
    KEY_ENDCALL                 = MAKE_KEYCODE(SCANCODE_ENDCALL),

    KEY_LEFT_TAB                = MAKE_EXTENDED_KEYCODE(1),
    KEY_LEVEL5_SHIFT            = MAKE_EXTENDED_KEYCODE(2),
    KEY_MULTI_KEY_COMPOSE       = MAKE_EXTENDED_KEYCODE(3),
    KEY_LMETA                   = MAKE_EXTENDED_KEYCODE(4),
    KEY_RMETA                   = MAKE_EXTENDED_KEYCODE(5),
    KEY_LHYPER                  = MAKE_EXTENDED_KEYCODE(6),
    KEY_RHYPER                  = MAKE_EXTENDED_KEYCODE(7)
};

#undef MAKE_EXTENDED_KEYCODE
#undef MAKE_KEYCODE

enum key_mod : uint16_t
{
    MOD_NONE = 0,

    MOD_LSHIFT = (1 << 1),
    MOD_RSHIFT = (1 << 2),
    MOD_LEVEL5 = (1 << 3),
    MOD_SHIFT = (MOD_LSHIFT | MOD_RSHIFT),

    MOD_LCTRL = (1 << 4),
    MOD_RCTRL = (1 << 5),
    MOD_CTRL = (MOD_LCTRL | MOD_RCTRL),

    MOD_LALT = (1 << 6),
    MOD_RALT = (1 << 7),
    MOD_ALT = (MOD_LALT | MOD_RALT),

    MOD_LGUI = (1 << 8),
    MOD_RGUI = (1 << 9),
    MOD_GUI = (MOD_LGUI | MOD_RGUI),

    MOD_NUM = (1 << 10),
    MOD_CAPS = (1 << 11),

    MOD_MODE = (1 << 12),
    MOD_SCROLL = (1 << 13)
};

} // namespace keyboard
} // namespace app
} // namespace vx