#pragma once

#include "vertex/config/version_number.hpp"

#define VX_VERSION_MAJOR 0
#define VX_VERSION_MINOR 1
#define VX_VERSION_PATCH 0

#define VX_VERSION_STRING VX_MAKE_VERSION_STRING(VX_VERSION_MAJOR, VX_VERSION_MINOR, VX_VERSION_PATCH)

#define VX_VERSION VX_VERSION_NUMBER(VX_VERSION_MAJOR, VX_VERSION_MINOR, VX_VERSION_PATCH)