#pragma once

// ------------------------------------------------------------
// Backend lifecycle
// ------------------------------------------------------------

#ifdef VX_VIDEO_HAVE_INIT
#   undef VX_VIDEO_HAVE_INIT
#endif
#define VX_VIDEO_HAVE_INIT 1

#ifdef VX_VIDEO_HAVE_QUIT
#   undef VX_VIDEO_HAVE_QUIT
#endif
#define VX_VIDEO_HAVE_QUIT 1

// ------------------------------------------------------------
// Display management
// ------------------------------------------------------------

#ifdef VX_VIDEO_HAVE_DISPLAY_UPDATE
#   undef VX_VIDEO_HAVE_DISPLAY_UPDATE
#endif
#define VX_VIDEO_HAVE_DISPLAY_UPDATE 1

#ifdef VX_VIDEO_HAVE_DISPLAY_LIST_MODES
#   undef VX_VIDEO_HAVE_DISPLAY_LIST_MODES
#endif
#define VX_VIDEO_HAVE_DISPLAY_LIST_MODES 1

#ifdef VX_VIDEO_HAVE_DISPLAY_SET_MODE
#   undef VX_VIDEO_HAVE_DISPLAY_SET_MODE
#endif
#define VX_VIDEO_HAVE_DISPLAY_SET_MODE 1

#ifdef VX_VIDEO_HAVE_DISPLAY_GET_BOUNDS
#   undef VX_VIDEO_HAVE_DISPLAY_GET_BOUNDS
#endif
#define VX_VIDEO_HAVE_DISPLAY_GET_BOUNDS 1

#ifdef VX_VIDEO_HAVE_DISPLAY_GET_WORK_AREA
#   undef VX_VIDEO_HAVE_DISPLAY_GET_WORK_AREA
#endif
#define VX_VIDEO_HAVE_DISPLAY_GET_WORK_AREA 1

#ifdef VX_VIDEO_SENDS_FULLSCREEN_DIMENSIONS
#   undef VX_VIDEO_SENDS_FULLSCREEN_DIMENSIONS
#endif
#define VX_VIDEO_SENDS_FULLSCREEN_DIMENSIONS 1

// ------------------------------------------------------------
// Event handling
// ------------------------------------------------------------

#ifdef VX_VIDEO_HAVE_PUMP_EVENTS
#   undef VX_VIDEO_HAVE_PUMP_EVENTS
#endif
#define VX_VIDEO_HAVE_PUMP_EVENTS 1

#ifdef VX_VIDEO_HAVE_WAIT_EVENT_TIMEOUT
#   undef VX_VIDEO_HAVE_WAIT_EVENT_TIMEOUT
#endif
#define VX_VIDEO_HAVE_WAIT_EVENT_TIMEOUT 1

#ifdef VX_VIDEO_HAVE_SEND_WAKEUP_EVENT
#   undef VX_VIDEO_HAVE_SEND_WAKEUP_EVENT
#endif
#define VX_VIDEO_HAVE_SEND_WAKEUP_EVENT 1

#ifdef VX_VIDEO_HAVE_SUSPEND_SCREEN_SAVER
#   undef VX_VIDEO_HAVE_SUSPEND_SCREEN_SAVER
#endif
#define VX_VIDEO_HAVE_SUSPEND_SCREEN_SAVER 1

// ------------------------------------------------------------
// Window management
// ------------------------------------------------------------

#ifdef VX_VIDEO_HAVE_POPUP_WINDOW_SUPPORT
#   undef VX_VIDEO_HAVE_POPUP_WINDOW_SUPPORT
#endif
#define VX_VIDEO_HAVE_POPUP_WINDOW_SUPPORT 1

#ifdef VX_VIDEO_HAVE_WINDOW_CREATE
#   undef VX_VIDEO_HAVE_WINDOW_CREATE
#endif
#define VX_VIDEO_HAVE_WINDOW_CREATE 1

#ifdef VX_VIDEO_HAVE_WINDOW_DESTROY
#   undef VX_VIDEO_HAVE_WINDOW_DESTROY
#endif
#define VX_VIDEO_HAVE_WINDOW_DESTROY 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_TITLE
#   undef VX_VIDEO_HAVE_WINDOW_SET_TITLE
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_TITLE 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_ICON
#   undef VX_VIDEO_HAVE_WINDOW_SET_ICON
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_ICON 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_POSITION
#   undef VX_VIDEO_HAVE_WINDOW_SET_POSITION
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_POSITION 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_SIZE
#   undef VX_VIDEO_HAVE_WINDOW_SET_SIZE
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_SIZE 1

#ifdef VX_VIDEO_HAVE_WINDOW_GET_BORDER_SIZE
#   undef VX_VIDEO_HAVE_WINDOW_GET_BORDER_SIZE
#endif
#define VX_VIDEO_HAVE_WINDOW_GET_BORDER_SIZE 1

#ifdef VX_VIDEO_HAVE_WINDOW_GET_PIXEL_SIZE
#   undef VX_VIDEO_HAVE_WINDOW_GET_PIXEL_SIZE
#endif
#define VX_VIDEO_HAVE_WINDOW_GET_PIXEL_SIZE 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_OPACITY
#   undef VX_VIDEO_HAVE_WINDOW_SET_OPACITY
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_OPACITY 1

#ifdef VX_VIDEO_HAVE_WINDOW_SHOW
#   undef VX_VIDEO_HAVE_WINDOW_SHOW
#endif
#define VX_VIDEO_HAVE_WINDOW_SHOW 1

#ifdef VX_VIDEO_HAVE_WINDOW_HIDE
#   undef VX_VIDEO_HAVE_WINDOW_HIDE
#endif
#define VX_VIDEO_HAVE_WINDOW_HIDE 1

#ifdef VX_VIDEO_HAVE_WINDOW_RAISE
#   undef VX_VIDEO_HAVE_WINDOW_RAISE
#endif
#define VX_VIDEO_HAVE_WINDOW_RAISE 1

#ifdef VX_VIDEO_HAVE_WINDOW_MAXIMIZE
#   undef VX_VIDEO_HAVE_WINDOW_MAXIMIZE
#endif
#define VX_VIDEO_HAVE_WINDOW_MAXIMIZE 1

#ifdef VX_VIDEO_HAVE_WINDOW_MINIMIZE
#   undef VX_VIDEO_HAVE_WINDOW_MINIMIZE
#endif
#define VX_VIDEO_HAVE_WINDOW_MINIMIZE 1

#ifdef VX_VIDEO_HAVE_WINDOW_RESTORE
#   undef VX_VIDEO_HAVE_WINDOW_RESTORE
#endif
#define VX_VIDEO_HAVE_WINDOW_RESTORE 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_BORDERED
#   undef VX_VIDEO_HAVE_WINDOW_SET_BORDERED
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_BORDERED 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_RESIZABLE
#   undef VX_VIDEO_HAVE_WINDOW_SET_RESIZABLE
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_RESIZABLE 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_ALWAYS_ON_TOP
#   undef VX_VIDEO_HAVE_WINDOW_SET_ALWAYS_ON_TOP
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_ALWAYS_ON_TOP 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_FULLSCREEN
#   undef VX_VIDEO_HAVE_WINDOW_SET_FULLSCREEN
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_FULLSCREEN 1

#ifdef VX_VIDEO_HAVE_WINDOW_GET_ICC_PROFILE
#   undef VX_VIDEO_HAVE_WINDOW_GET_ICC_PROFILE
#endif
#define VX_VIDEO_HAVE_WINDOW_GET_ICC_PROFILE 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_MOUSE_RECT
#   undef VX_VIDEO_HAVE_WINDOW_SET_MOUSE_RECT
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_MOUSE_RECT 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_MOUSE_GRAB
#   undef VX_VIDEO_HAVE_WINDOW_SET_MOUSE_GRAB
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_MOUSE_GRAB 1

#ifdef VX_VIDEO_HAVE_WINDOW_SET_KEYBOARD_GRAB
#   undef VX_VIDEO_HAVE_WINDOW_SET_KEYBOARD_GRAB
#endif
#define VX_VIDEO_HAVE_WINDOW_SET_KEYBOARD_GRAB 1

// ------------------------------------------------------------
// Text input
// ------------------------------------------------------------

#ifdef VX_VIDEO_HAVE_TEXT_INPUT_START
#   undef VX_VIDEO_HAVE_TEXT_INPUT_START
#endif
#define VX_VIDEO_HAVE_TEXT_INPUT_START 1

#ifdef VX_VIDEO_HAVE_TEXT_INPUT_STOP
#   undef VX_VIDEO_HAVE_TEXT_INPUT_STOP
#endif
#define VX_VIDEO_HAVE_TEXT_INPUT_STOP 1

#ifdef VX_VIDEO_HAVE_TEXT_INPUT_UPDATE_AREA
#   undef VX_VIDEO_HAVE_TEXT_INPUT_UPDATE_AREA
#endif
#define VX_VIDEO_HAVE_TEXT_INPUT_UPDATE_AREA 1

#ifdef VX_VIDEO_HAVE_TEXT_INPUT_CLEAR_COMPOSITION
#   undef VX_VIDEO_HAVE_TEXT_INPUT_CLEAR_COMPOSITION
#endif
#define VX_VIDEO_HAVE_TEXT_INPUT_CLEAR_COMPOSITION 1

// ------------------------------------------------------------
// Clipboard
// ------------------------------------------------------------

#ifdef VX_VIDEO_HAVE_CLIPBOARD_SET_DATA
#   undef VX_VIDEO_HAVE_CLIPBOARD_SET_DATA
#endif
#define VX_VIDEO_HAVE_CLIPBOARD_SET_DATA 1

#ifdef VX_VIDEO_HAVE_CLIPBOARD_GET_DATA
#   undef VX_VIDEO_HAVE_CLIPBOARD_GET_DATA
#endif
#define VX_VIDEO_HAVE_CLIPBOARD_GET_DATA 1

#ifdef VX_VIDEO_HAVE_CLIPBOARD_HAS_DATA
#   undef VX_VIDEO_HAVE_CLIPBOARD_HAS_DATA
#endif
#define VX_VIDEO_HAVE_CLIPBOARD_HAS_DATA 1

#ifdef VX_VIDEO_HAVE_CLIPBOARD_SCREEN_KEYBOARD
#   undef VX_VIDEO_HAVE_CLIPBOARD_SCREEN_KEYBOARD
#endif
#define VX_VIDEO_HAVE_CLIPBOARD_SCREEN_KEYBOARD 1