#pragma once

// ------------------------------------------------------------
// Backend lifecycle
// ------------------------------------------------------------

#ifdef VX_VIDEO_BACKEND_HAVE_INIT
#   undef VX_VIDEO_BACKEND_HAVE_INIT
#endif
#define VX_VIDEO_BACKEND_HAVE_INIT 1

#ifdef VX_VIDEO_BACKEND_HAVE_QUIT
#   undef VX_VIDEO_BACKEND_HAVE_QUIT
#endif
#define VX_VIDEO_BACKEND_HAVE_QUIT 1

// ------------------------------------------------------------
// Display management
// ------------------------------------------------------------

#ifdef VX_VIDEO_BACKEND_HAVE_REFRESH_DISPLAYS
#   undef VX_VIDEO_BACKEND_HAVE_REFRESH_DISPLAYS
#endif
#define VX_VIDEO_BACKEND_HAVE_REFRESH_DISPLAYS 1

#ifdef VX_VIDEO_BACKEND_HAVE_DISPLAY_LIST_MODES
#   undef VX_VIDEO_BACKEND_HAVE_DISPLAY_LIST_MODES
#endif
#define VX_VIDEO_BACKEND_HAVE_DISPLAY_LIST_MODES 1

#ifdef VX_VIDEO_BACKEND_HAVE_DISPLAY_SET_MODE
#   undef VX_VIDEO_BACKEND_HAVE_DISPLAY_SET_MODE
#endif
#define VX_VIDEO_BACKEND_HAVE_DISPLAY_SET_MODE 1

#ifdef VX_VIDEO_BACKEND_HAVE_DISPLAY_GET_BOUNDS
#   undef VX_VIDEO_BACKEND_HAVE_DISPLAY_GET_BOUNDS
#endif
#define VX_VIDEO_BACKEND_HAVE_DISPLAY_GET_BOUNDS 1

#ifdef VX_VIDEO_BACKEND_HAVE_DISPLAY_GET_WORK_AREA
#   undef VX_VIDEO_BACKEND_HAVE_DISPLAY_GET_WORK_AREA
#endif
#define VX_VIDEO_BACKEND_HAVE_DISPLAY_GET_WORK_AREA 1

// ------------------------------------------------------------
// Display features
// ------------------------------------------------------------

#ifdef VX_VIDEO_BACKEND_SENDS_FULLSCREEN_DIMENSIONS
#   undef VX_VIDEO_BACKEND_SENDS_FULLSCREEN_DIMENSIONS
#endif
#define VX_VIDEO_BACKEND_SENDS_FULLSCREEN_DIMENSIONS 1

#ifdef VX_VIDEO_BACKEND_HAVE_POPUP_WINDOW_SUPPORT
#   undef VX_VIDEO_BACKEND_HAVE_POPUP_WINDOW_SUPPORT
#endif
#define VX_VIDEO_BACKEND_HAVE_POPUP_WINDOW_SUPPORT 1

#ifdef VX_VIDEO_BACKEND_HAVE_SUSPEND_SCREEN_SAVER
#   undef VX_VIDEO_BACKEND_HAVE_SUSPEND_SCREEN_SAVER
#endif
#define VX_VIDEO_BACKEND_HAVE_SUSPEND_SCREEN_SAVER 1

#ifdef VX_VIDEO_BACKEND_HAVE_GET_SYSTEM_THEME
#   undef VX_VIDEO_BACKEND_HAVE_GET_SYSTEM_THEME
#endif
#define VX_VIDEO_BACKEND_HAVE_GET_SYSTEM_THEME 1

// ------------------------------------------------------------
// Event handling
// ------------------------------------------------------------

#ifdef VX_VIDEO_BACKEND_HAVE_PUMP_EVENTS
#   undef VX_VIDEO_BACKEND_HAVE_PUMP_EVENTS
#endif
#define VX_VIDEO_BACKEND_HAVE_PUMP_EVENTS 1

#ifdef VX_VIDEO_BACKEND_HAVE_WAIT_EVENT_TIMEOUT
#   undef VX_VIDEO_BACKEND_HAVE_WAIT_EVENT_TIMEOUT
#endif
#define VX_VIDEO_BACKEND_HAVE_WAIT_EVENT_TIMEOUT 1

#ifdef VX_VIDEO_BACKEND_HAVE_SEND_WAKEUP_EVENT
#   undef VX_VIDEO_BACKEND_HAVE_SEND_WAKEUP_EVENT
#endif
#define VX_VIDEO_BACKEND_HAVE_SEND_WAKEUP_EVENT 1

// ------------------------------------------------------------
// Window management
// ------------------------------------------------------------

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_CREATE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_CREATE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_CREATE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_DESTROY
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_DESTROY
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_DESTROY 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_TITLE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_TITLE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_TITLE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_ICON
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_ICON
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_ICON 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_POSITION
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_POSITION
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_POSITION 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_SIZE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_SIZE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_SIZE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_GET_BORDER_SIZE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_GET_BORDER_SIZE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_GET_BORDER_SIZE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_GET_SIZE_IN_PIXELS
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_GET_SIZE_IN_PIXELS
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_GET_SIZE_IN_PIXELS 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_OPACITY
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_OPACITY
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_OPACITY 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SHOW
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SHOW
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SHOW 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_HIDE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_HIDE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_HIDE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_RAISE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_RAISE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_RAISE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_MAXIMIZE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_MAXIMIZE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_MAXIMIZE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_MINIMIZE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_MINIMIZE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_MINIMIZE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_RESTORE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_RESTORE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_RESTORE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_FLASH
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_FLASH
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_FLASH 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_BORDERED
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_BORDERED
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_BORDERED 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_RESIZABLE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_RESIZABLE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_RESIZABLE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_ALWAYS_ON_TOP
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_ALWAYS_ON_TOP
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_ALWAYS_ON_TOP 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_FULLSCREEN
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_FULLSCREEN
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_FULLSCREEN 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_GET_ICC_PROFILE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_GET_ICC_PROFILE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_GET_ICC_PROFILE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_MOUSE_RECT
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_MOUSE_RECT
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_MOUSE_RECT 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_MOUSE_GRAB
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_MOUSE_GRAB
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_MOUSE_GRAB 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_ON_MOUSE_ENTER
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_ON_MOUSE_ENTER
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_ON_MOUSE_ENTER 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_KEYBOARD_GRAB
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_KEYBOARD_GRAB
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_KEYBOARD_GRAB 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_UPDATE_SHAPE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_UPDATE_SHAPE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_UPDATE_SHAPE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_FOCUSABLE
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_SET_FOCUSABLE
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_SET_FOCUSABLE 1

#ifdef VX_VIDEO_BACKEND_HAVE_WINDOW_ACCEPT_DRAG_AND_DROP
#   undef VX_VIDEO_BACKEND_HAVE_WINDOW_ACCEPT_DRAG_AND_DROP
#endif
#define VX_VIDEO_BACKEND_HAVE_WINDOW_ACCEPT_DRAG_AND_DROP 1

// ------------------------------------------------------------
// Mouse
// ------------------------------------------------------------

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_CREATE_CURSOR
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_CREATE_CURSOR
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_CREATE_CURSOR 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_CREATE_SYSTEM_CURSOR
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_CREATE_SYSTEM_CURSOR
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_CREATE_SYSTEM_CURSOR 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_SHOW_CURSOR
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_SHOW_CURSOR
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_SHOW_CURSOR 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_MOVE_CURSOR
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_MOVE_CURSOR
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_MOVE_CURSOR 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_FREE_CURSOR
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_FREE_CURSOR
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_FREE_CURSOR 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_WARP
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_WARP
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_WARP 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_WARP_GLOBAL
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_WARP_GLOBAL
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_WARP_GLOBAL 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_SET_RELATIVE_MOUSE_MODE
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_SET_RELATIVE_MOUSE_MODE
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_SET_RELATIVE_MOUSE_MODE 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_CAPTURE_MOUSE
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_CAPTURE_MOUSE
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_CAPTURE_MOUSE 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_GET_GLOBAL_MOUSE_STATE
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_GET_GLOBAL_MOUSE_STATE
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_GET_GLOBAL_MOUSE_STATE 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_GET_DOUBLE_CLICK_TIME
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_GET_DOUBLE_CLICK_TIME
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_GET_DOUBLE_CLICK_TIME 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_GET_DOUBLE_CLICK_AREA
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_GET_DOUBLE_CLICK_AREA
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_GET_DOUBLE_CLICK_AREA 1

#ifdef VX_VIDEO_BACKEND_HAVE_MOUSE_APPLY_SYSTEM_SCALE
#   undef VX_VIDEO_BACKEND_HAVE_MOUSE_APPLY_SYSTEM_SCALE
#endif
#define VX_VIDEO_BACKEND_HAVE_MOUSE_APPLY_SYSTEM_SCALE 1

// ------------------------------------------------------------
// Text input
// ------------------------------------------------------------

#ifdef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_START
#   undef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_START
#endif
#define VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_START 1

#ifdef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_STOP
#   undef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_STOP
#endif
#define VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_STOP 1

#ifdef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_UPDATE_AREA
#   undef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_UPDATE_AREA
#endif
#define VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_UPDATE_AREA 1

#ifdef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_CLEAR_COMPOSITION
#   undef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_CLEAR_COMPOSITION
#endif
#define VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_CLEAR_COMPOSITION 1

#ifdef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_SHOW_SCREEN_KEYBOARD
#   undef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_SHOW_SCREEN_KEYBOARD
#endif
#define VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_SHOW_SCREEN_KEYBOARD 1

#ifdef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_HIDE_SCREEN_KEYBOARD
#   undef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_HIDE_SCREEN_KEYBOARD
#endif
#define VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_HIDE_SCREEN_KEYBOARD 1

#ifdef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_HAS_SCREEN_KEYBOARD_SUPPORT
#   undef VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_HAS_SCREEN_KEYBOARD_SUPPORT
#endif
#define VX_VIDEO_BACKEND_HAVE_TEXT_INPUT_HAS_SCREEN_KEYBOARD_SUPPORT 1

// ------------------------------------------------------------
// Clipboard
// ------------------------------------------------------------

#ifdef VX_VIDEO_BACKEND_HAVE_CLIPBOARD_SET_DATA
#   undef VX_VIDEO_BACKEND_HAVE_CLIPBOARD_SET_DATA
#endif
#define VX_VIDEO_BACKEND_HAVE_CLIPBOARD_SET_DATA 1

#ifdef VX_VIDEO_BACKEND_HAVE_CLIPBOARD_GET_DATA
#   undef VX_VIDEO_BACKEND_HAVE_CLIPBOARD_GET_DATA
#endif
#define VX_VIDEO_BACKEND_HAVE_CLIPBOARD_GET_DATA 1

#ifdef VX_VIDEO_BACKEND_HAVE_CLIPBOARD_HAS_DATA
#   undef VX_VIDEO_BACKEND_HAVE_CLIPBOARD_HAS_DATA
#endif
#define VX_VIDEO_BACKEND_HAVE_CLIPBOARD_HAS_DATA 1